/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.20
 * Generated at: 2024-04-26 05:09:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class SolicitarInscripcion_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/jquery.dataTables.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/dataTables.bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrap.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/global.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"js/bootstrapValidator.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/style.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/form-elements.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrapValidator.css\">\r\n");
      out.write("<meta charset=\"ISO-8859-1\">\r\n");
      out.write("\r\n");
      out.write("<title>Solicitud de Inscripción</title>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("h4{\r\n");
      out.write("font-family: impact;\r\n");
      out.write("	color: balck;\r\n");
      out.write("	font-size: 60px;\r\n");
      out.write("	text-align:center;\r\n");
      out.write("	text-shadow: 5px 5px 5px white;\r\n");
      out.write("	margin: 0px auto 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("select {\r\n");
      out.write("height: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("	margin-top: 10%;\r\n");
      out.write("	background-color:lightblue;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	box-shadow: 5px 5px 5px lightblue;\r\n");
      out.write("	width: 65%;\r\n");
      out.write("	height: 40%;\r\n");
      out.write("	padding: 40px;\r\n");
      out.write("	\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("	width: 200px;\r\n");
      out.write("	height: 30px;\r\n");
      out.write("	border-radius: 20px;\r\n");
      out.write("	margin: 20px;\r\n");
      out.write("	font-family: impact;\r\n");
      out.write("	color: white;\r\n");
      out.write("	background-color: white;\r\n");
      out.write("}\r\n");
      out.write("\n");
      out.write("\r\n");
      out.write("\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"container\" style=\"margin-top: 4%\">\r\n");
      out.write("		<h4 style=\"text-align: center\">Registrar Solicitante</h4>\r\n");
      out.write("		<form id=\"id_form\">\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_nombr\">Nombres y Apellidos</label> <input\r\n");
      out.write("						class=\"form-control\" type=\"text\" id=\"id_nombre\" name=\"nombre\"\r\n");
      out.write("						placeholder=\"Ingrese sus nombres y apellidos\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_empres\">Empresa</label> <input\r\n");
      out.write("						class=\"form-control\" type=\"text\" id=\"id_empresa\"\r\n");
      out.write("						name=\"apellidos\" placeholder=\"Ingrese la empresa\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-2\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_dn\">DNI</label> \r\n");
      out.write("					<input class=\"form-control\" type=\"text\" id=\"id_dni\" name=\"dni\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-2\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_fechaNacimiento\">Fecha\r\n");
      out.write("						de Nacimiento</label> <input class=\"form-control\" type=\"date\"\r\n");
      out.write("						id=\"id_fechaNacimiento\" name=\"fechaNacimiento\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\" style=\"display: flex; justify-content: center\">\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_grad\"> Grado Académico </label> <select class=\"form-control\" id=\"id_grado\" name=\"grado\">\r\n");
      out.write("						<option value=\"\">[Seleccione]</option>\r\n");
      out.write("						<option value=\"1\">Secundaria</option>\r\n");
      out.write("						<option value=\"2\">Técnico Superior</option>\r\n");
      out.write("						<option value=\"3\">Universitario</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_puest\"> Puesto </label> \r\n");
      out.write("					<select class=\"form-control\" id=\"id_puesto\" name=\"puesto\">\r\n");
      out.write("						<option value=\"\">[Seleccione]</option>\r\n");
      out.write("						<option value=\"1\">Rigger</option>\r\n");
      out.write("						<option value=\"2\">Operador</option>\r\n");
      out.write("						<option value=\"3\">Mecánico</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_expe\">Años de experiencia</label>\r\n");
      out.write("						<select class=\"form-control\" id=\"id_exp\" name=\"experiencia\">\r\n");
      out.write("						<option value=\"\">[Seleccione]</option>\r\n");
      out.write("						<option value=\"1\">2 años</option>\r\n");
      out.write("						<option value=\"2\">3 años</option>\r\n");
      out.write("						<option value=\"3\">4 años</option>\r\n");
      out.write("						<option value=\"4\">5 a 10 años</option>\r\n");
      out.write("						<option value=\"5\">11 a 20 años</option>\r\n");
      out.write("					</select>\r\n");
      out.write("				</div>\r\n");
      out.write("				\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"row\" style=\"display: flex; justify-content: center\">\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_corre\">Correo</label> <input\r\n");
      out.write("						class=\"form-control\" type=\"text\" id=\"id_correo\" name=\"correo\">\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"form-group col-md-4\">\r\n");
      out.write("					<label class=\"control-label\" for=\"id_tele\">Teléfono</label> <input\r\n");
      out.write("						class=\"form-control\" type=\"text\" id=\"id_telefono\" name=\"telefono\">\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"row\" align=\"center\" style=\"margin-top: 2%\">\r\n");
      out.write("				<button type=\"button\" class=\"btn btn-primary\" id=\"id_btn_registra\">REGISTRAR</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(document)\r\n");
      out.write("				.ready(\r\n");
      out.write("						function() {\r\n");
      out.write("							$('#id_form')\r\n");
      out.write("									.bootstrapValidator(\r\n");
      out.write("											{\r\n");
      out.write("												message : 'This value is not valid',\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("												fields : {\r\n");
      out.write("													nombre : {\r\n");
      out.write("														selector : \"#id_nombre\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'Los nombres y apellidos son requeridos'\r\n");
      out.write("															},\r\n");
      out.write("															stringLength : {\r\n");
      out.write("																min : 10,\r\n");
      out.write("																max : 100,\r\n");
      out.write("																message : 'Los nombres tiene de 10 a 100 caracteres'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("\r\n");
      out.write("													empresa : {\r\n");
      out.write("														selector : \"#id_empresa\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'La empresa es requerida'\r\n");
      out.write("\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("													\r\n");
      out.write("													dni : {\r\n");
      out.write("														selector : \"#id_dni\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'El DNI es requerido'\r\n");
      out.write("															},\r\n");
      out.write("															stringLength : {\r\n");
      out.write("																min : 8,\r\n");
      out.write("																max : 8,\r\n");
      out.write("																message : 'El DNI tiene 8 dígitos '\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("\r\n");
      out.write("													fechaNacimieento : {\r\n");
      out.write("														selector : \"#id_fechaNacimiento\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'La fecha de nacimiento es requerida'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("\r\n");
      out.write("													telefono : {\r\n");
      out.write("														selector : \"#id_telefono\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'El telefono es requerido'\r\n");
      out.write("															},\r\n");
      out.write("															stringLength : {\r\n");
      out.write("																min : 9,\r\n");
      out.write("																max : 9,\r\n");
      out.write("																message : 'El teléfono tiene 9 caracteres'\r\n");
      out.write("															}\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("													grado : {\r\n");
      out.write("														selector : \"#id_grado\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'El grado académico es requerido'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("													experiencia : {\r\n");
      out.write("														selector : \"#id_exp\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'Los años de experiencia es requerido'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("													experiencia : {\r\n");
      out.write("														selector : \"#id_exp\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'Los años de experiencia es requerido'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("													correo : {\r\n");
      out.write("														selector : \"#id_correo\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'El correo es requerido'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("													puesto : {\r\n");
      out.write("														selector : \"#id_puesto\",\r\n");
      out.write("														validators : {\r\n");
      out.write("															notEmpty : {\r\n");
      out.write("																message : 'El puesto es requerido'\r\n");
      out.write("															},\r\n");
      out.write("														}\r\n");
      out.write("													},\r\n");
      out.write("												}\r\n");
      out.write("\r\n");
      out.write("											});\r\n");
      out.write("\r\n");
      out.write("						});\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script type=\"text/javascript\">\r\n");
      out.write("		$(\"#id_btn_registra\").click(function() {\r\n");
      out.write("			var validator = $('#id_form').data('bootstrapValidator');\r\n");
      out.write("			validator.validate();\r\n");
      out.write("\r\n");
      out.write("			if (validator.isValid()) {\r\n");
      out.write("				$.ajax({\r\n");
      out.write("					type : \"POST\",\r\n");
      out.write("					url : \"registraAutor\",\r\n");
      out.write("					data : $('#id_form').serialize(),\r\n");
      out.write("					success : function(data) {\r\n");
      out.write("						mostrarMensaje(data.mensaje);\r\n");
      out.write("						limpiarFormulario();\r\n");
      out.write("						validator.resetForm();\r\n");
      out.write("					},\r\n");
      out.write("					error : function() {\r\n");
      out.write("						limpiarFormulario();\r\n");
      out.write("						mostrarMensaje(MSG_ERROR);\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$.getJSON(\"comboGrado\", {}, function(data) {\r\n");
      out.write("			$.each(data, function(index, item) {\r\n");
      out.write("				$(\"#id_grado\").append(\r\n");
      out.write("						\"<option value=\" +  item.idGrado +\" >\" + item.descripcion + \"</option>\");\r\n");
      out.write("			});\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		function limpiarFormulario() {\r\n");
      out.write("			$('#id_nombre').val('');\r\n");
      out.write("			$('#id_empresa').val('');\r\n");
      out.write("			$('#id_dni').val('');\r\n");
      out.write("			$('#id_fechaNacimiento').val('');\r\n");
      out.write("			$('#id_telefono').val(' ');\r\n");
      out.write("			$('#id_grado').val(' ');\r\n");
      out.write("			$('#id_puesto').val('');\r\n");
      out.write("			$('#id_exp').val('');\r\n");
      out.write("			$('#id_correo').val('');\r\n");
      out.write("		}\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
